//! **The record of the detector firing on a defect planted before it existed.**
//!
//! This file used to assert a *failure*. It planted a realistic lookahead
//! defect — [`LeakyZScore`][crucible_strategies::controls::LeakyZScore], which
//! standardizes each close against the mean and standard deviation of the
//! **whole series**, the exact failure §2.1 names — ran it on the project's own
//! null harness, showed it made money out of sample under honest costs while
//! beating both mandatory controls, and asserted the criteria returned
//! `Iterate`. That assertion was the measured cost of not having a detector.
//!
//! **The permutation null landed 2026-07-31 (D-0087) and the expectation
//! flipped to `Kill`.** Nothing else changed: not the strategy, not its
//! registration, not a threshold. The flip is the acceptance test of
//! `docs/MILESTONES.md`'s last M3 clause, and it was reached the only way §9
//! permits — by building the harness.
//!
//! **What the harness sees that the gates cannot.** Every criterion before S3
//! still passes, and this file asserts that too: admission, S1, S2's Sharpe,
//! S2's kill-level sweep, and both controls. A statistic computed *on the
//! leaked run* cannot separate a leaked edge from a real one, which is why
//! tightening any of those thresholds was always the wrong repair. The
//! permutation null asks a different question — *would this strategy have
//! produced the same result on a series with the same shape but no long-range
//! ordering?* — and the leak answers **yes**, because it simply re-fits on
//! every permutation. Its observed run is an ordinary draw from its own null:
//! `p = 0.2079` against a pre-registered `0.05`.
//!
//! The assertion that every pre-S3 gate still passes is not decoration. If a
//! future change made the leak die at S1 or S2 instead, the verdict would still
//! read `Kill` while this file had stopped measuring the permutation null.

use crucible_core::prelude::*;
use crucible_engine::{BacktestParams, FreeFills, SpreadCrossFills, Summary, run};
use crucible_funnel::stages::{Criteria, CriteriaSource, Evidence, Stage, Verdict, assess};
use crucible_funnel::walkforward::{FoldPlan, FoldScheme, FoldSpec, RunTrace};
use crucible_strategies::controls::{BuyAndHold, LeakyZScore};
use crucible_strategies::{MatchedEpisode, RandomEntry};

/// The same shape as the null-harness config — a seeded random walk with an
/// ES-like contract — but **seed 29 rather than the smoke config's 42, and a
/// denser fold layout**. The reason is worth stating, because choosing a seed
/// looks like fixture-fitting and here it is the opposite of it.
///
/// Buy-and-hold is a *criterion*, and a random walk's drift over any
/// particular set of out-of-sample windows is arbitrary. On seed 42 the walk
/// rises 4.5 % across the test windows, which is more than the leak's edge, so
/// the leak is killed — correctly, by the buy-and-hold rule, and for a reason
/// with nothing to do with the leak. That would make this file a measurement
/// of which way a random walk happened to go.
///
/// Seed 29's walk moves **−0.04 %** across its test windows: as close to no
/// drift as this generator offers. With the market's own return removed from
/// the comparison, what is left is the leak against the criteria, which is
/// what the file claims to measure. Measured across eighteen seeds before
/// choosing, and the choice is the one that makes the *gates' job easiest* —
/// the claim being recorded is that they fail to catch the leak even with
/// nothing else in the way.
const SEED: u64 = 29;
const BARS: usize = 20_000;
/// Bands the leaked z-score flips at. Chosen so the leak closes enough
/// round-trips inside the test windows to clear the sample-adequacy gate —
/// otherwise it dies at S0 for having nothing to measure, which is again not
/// the fact under test.
const ENTRY_Z: f64 = 0.5;
/// Denser than the smoke config's 5/2/2 for the same reason: more test windows
/// means more round-trips close out of sample.
const FOLDS: FoldSpec = FoldSpec {
    scheme: FoldScheme::Rolling,
    train_days: 3,
    test_days: 1,
    step_days: 1,
};

fn spec() -> ContractSpec {
    ContractSpec {
        instrument: InstrumentId::new("SYN:RW"),
        tick: Price::from_points_f64_lossy(0.25),
        point_value_usd: 50,
    }
}

fn params() -> BacktestParams {
    BacktestParams {
        initial_cash_nano_usd: 100_000_000_000_000,
        bars_per_year: 347_760.0,
    }
}

fn costed() -> SpreadCrossFills {
    SpreadCrossFills::from_ticks(1, spec().tick).with_fee(1_250_000_000)
}

/// The seeded random walk `configs/combo-smoke.toml` replays, materialized.
///
/// Generated by the same `SyntheticFeed` the CLI uses (D-0011), so this is the
/// project's own null harness and not a fixture built to make a point.
fn events() -> Vec<MarketEvent> {
    let mut feed = crucible_data::SyntheticFeed::random_walk(
        SEED,
        BARS,
        TimeFrame::M1,
        Price::from_points(5000),
        spec().tick,
        4,
    );
    std::iter::from_fn(|| feed.next_event()).collect()
}

/// One UTC civil day per 1,440 bars — what the CLI computes for an instrument
/// no calendar governs.
fn day_keys(n: usize) -> Vec<i64> {
    (0..n)
        .map(|i| i64::try_from(i / 1_440).unwrap_or(0))
        .collect()
}

struct SliceFeed<'a> {
    events: &'a [MarketEvent],
    at: usize,
}

impl Feed for SliceFeed<'_> {
    fn next_event(&mut self) -> Option<MarketEvent> {
        let event = self.events.get(self.at)?.clone();
        self.at += 1;
        Some(event)
    }
}

/// Rebuilds the event series from a permuted close path, keeping every bar's
/// timestamp and volume and moving only the prices.
///
/// OHLC collapses to the close on purpose: the permutation's null is about the
/// ordering of *returns*, and carrying the original bar's high/low onto a
/// different level would invent intrabar ranges the permuted path never had.
/// The leak reads closes and nothing else, so nothing under test is lost.
fn events_from_path(template: &[MarketEvent], path: &[f64]) -> Vec<MarketEvent> {
    assert_eq!(template.len(), path.len(), "one price per bar");
    template
        .iter()
        .zip(path.iter())
        .map(|(ev, px)| {
            let MarketEvent::Bar(b) = ev;
            let p = Price::from_points_f64_lossy(*px);
            let mut nb = b.clone();
            nb.open = p;
            nb.high = p;
            nb.low = p;
            nb.close = p;
            MarketEvent::Bar(nb)
        })
        .collect()
}

/// The leak, re-fitted on whatever series it is handed — which is precisely why
/// it survives permutation and why the null kills it.
fn leaky_on(events: &[MarketEvent]) -> LeakyZScore {
    let closes: Vec<Price> = events
        .iter()
        .map(|ev| {
            let MarketEvent::Bar(b) = ev;
            b.close
        })
        .collect();
    LeakyZScore::fit_on_everything(&closes, ENTRY_Z, Qty(1))
}

fn replay<S: Strategy, M: FillModel>(
    events: &[MarketEvent],
    strategy: &mut S,
    fills: &mut M,
) -> crucible_engine::BacktestResult {
    let mut feed = SliceFeed { events, at: 0 };
    run(&mut feed, strategy, fills, &spec(), &params()).expect("the synthetic feed is ordered")
}

fn pooled(result: &crucible_engine::BacktestResult, windows: &[std::ops::Range<usize>]) -> Summary {
    RunTrace::new(&result.equity, &result.closed_trades, &result.fee_events).pooled(
        windows,
        params().initial_cash_nano_usd,
        params().bars_per_year,
    )
}

/// The whole record, in one test so that the three facts cannot drift apart:
/// the leak is profitable, it beats both controls, and the gates pass it.
#[test]
fn the_planted_leak_is_caught_by_the_permutation_null() {
    let events = events();
    let keys = day_keys(events.len());
    let closes: Vec<Price> = events
        .iter()
        .map(|ev| {
            let MarketEvent::Bar(bar) = ev;
            bar.close
        })
        .collect();

    // The leak: fitted on every bar, including the ones after each decision.
    let warmup = 100;
    let plan = FoldPlan::build(&keys, warmup, FOLDS).expect("the null harness plans");
    let test_windows: Vec<std::ops::Range<usize>> =
        plan.folds().iter().map(|f| f.test.bars.clone()).collect();

    let leaky = || LeakyZScore::fit_on_everything(&closes, ENTRY_Z, Qty(1));
    let costed_run = replay(&events, &mut leaky(), &mut costed());
    let free_run = replay(&events, &mut leaky(), &mut FreeFills);
    let oos = pooled(&costed_run, &test_windows);
    let free_oos = pooled(&free_run, &test_windows);

    // Fact 1: on a random walk — where CLAUDE.md §9 says there is nothing to
    // find — the leak makes money out of sample AFTER honest costs.
    assert!(
        oos.total_return_pct > 0.0,
        "the planted leak must actually leak, or this record proves nothing: {:+.2}%",
        oos.total_return_pct
    );
    assert!(free_oos.total_return_pct > 0.0);
    assert!(
        oos.round_trips >= 5,
        "and it must trade enough to be judged: {} round-trips",
        oos.round_trips
    );

    // Fact 2: it beats both mandatory controls, replayed on the same bars
    // under the same fill model — so the denominators §7.4 requires do not
    // catch it either.
    let bnh = pooled(
        &replay(&events, &mut BuyAndHold::new(warmup, Qty(1)), &mut costed()),
        &test_windows,
    );
    let matched: Vec<(std::ops::Range<usize>, Vec<MatchedEpisode>)> = test_windows
        .iter()
        .map(|w| {
            let episodes = round_trips(&costed_run, &events)
                .into_iter()
                .filter(|&(_, close, _)| w.contains(&close))
                .map(|(open, close, direction)| MatchedEpisode {
                    holding_bars: (close - open.max(w.start)).max(1),
                    direction,
                })
                .collect();
            (w.clone(), episodes)
        })
        .collect();
    // The same 16-draw median the funnel uses: one draw is a sample of size
    // one, and a strategy can lose to a single coin flip by luck.
    let mut draws: Vec<f64> = (0..crucible_funnel::funnel::RANDOM_ENTRY_DRAWS)
        .map(|i| {
            let mut random = RandomEntry::matched_across(0xdead_beef + i as u64, &matched, Qty(1))
                .expect("the leak trades, so there is something to match");
            pooled(&replay(&events, &mut random, &mut costed()), &test_windows).total_return_pct
        })
        .collect();
    draws.sort_by(f64::total_cmp);
    let random_oos_pct = draws[(draws.len() - 1) / 2];

    assert!(
        oos.total_return_pct > bnh.total_return_pct,
        "{:+.2}% vs buy-and-hold {:+.2}%",
        oos.total_return_pct,
        bnh.total_return_pct
    );
    assert!(
        oos.total_return_pct > random_oos_pct,
        "{:+.2}% vs the matched random-entry median {random_oos_pct:+.2}% over {} draws",
        oos.total_return_pct,
        crucible_funnel::funnel::RANDOM_ENTRY_DRAWS
    );

    // Fact 3, and the reason this file exists: the pre-registered criteria say
    // ITERATE. Every gate this build runs is satisfied by a strategy whose
    // entire edge is knowledge of the future.
    // ---- THE PERMUTATION NULL (block A, docs/plans/m3-full.md).
    //
    // The leak standardizes against whatever series it is handed, so it
    // RE-FITS on every permutation and reproduces its edge there too. The
    // observed run is therefore an ordinary draw from its own null, and the
    // p-value says so. Nothing about the leaked result was extreme; the edge
    // is a property of being allowed to look, not of this data.
    let closes: Vec<f64> = events
        .iter()
        .map(|ev| {
            let MarketEvent::Bar(b) = ev;
            b.close.as_points_f64()
        })
        .collect();
    let observed = oos.total_return_pct;
    let perm = crucible_funnel::stats::permutation::run_permutation_null(
        &closes,
        observed,
        crucible_funnel::stats::permutation::PermutationSpec {
            // Twenty bars: longer than the leak's own reaction time and short
            // enough that a whole regime does not survive inside one block.
            // Declared, and swept in the harness's own tests (CLAUDE.md §9).
            block_len: 20,
            // 100 rather than 1,000: each draw is a full 20,000-bar replay, and
            // the p-value floor 1/(1+100) = 0.0099 is far below the 0.05 this
            // test judges against. Stated rather than tuned.
            draws: 100,
            seed: SEED,
        },
        |path| {
            let permuted = events_from_path(&events, path);
            let run = replay(&permuted, &mut leaky_on(&permuted), &mut costed());
            Some(pooled(&run, &test_windows).total_return_pct)
        },
    );
    let p_value = perm.p_value().expect("a null was built");
    eprintln!(
        "[permutation] leak: observed {observed:+.3}%, null median {:+.3}%, p = {p_value:.4}",
        perm.null[perm.null.len() / 2]
    );

    let criteria = criteria();
    let sessions: usize = plan.folds().iter().map(|f| f.test.n_days()).sum();
    let evidence = Evidence {
        oos_trades: oos.round_trips,
        oos_sessions: sessions,
        free_fill_return_pct: free_oos.total_return_pct,
        costed_return_pct: oos.total_return_pct,
        costed_sharpe: oos.sharpe_naive,
        sharpe_at_kill_level: pooled(
            &replay(
                &events,
                &mut leaky(),
                &mut SpreadCrossFills::from_tick_halves(2, spec().tick).with_fee(1_250_000_000),
            ),
            &test_windows,
        )
        .sharpe_naive,
        random_entry_return_pct: Some(random_oos_pct),
        permutation_p_value: Some(p_value),
        // Block B's two S3 gates are handed values that PASS, deliberately.
        // This test's whole claim is that the leak dies on the PERMUTATION
        // NULL and on nothing else — if deflation or PBO were also failing
        // here, the assertion below would still read `Kill` while having
        // stopped measuring the detector it is named after. Giving the other
        // two gates a clear pass is what keeps the permutation null the only
        // thing that can produce this verdict.
        deflated: Some(crucible_funnel::stats::deflated::Deflated {
            observed_sharpe: 4.0,
            expected_max_sharpe: 0.5,
            standard_error: 0.1,
            dsr: 0.999,
            n_trials: 1,
        }),
        n_trials: 1,
        pbo: Some(0.0),
        buy_and_hold_return_pct: Some(bnh.total_return_pct),
        // S0 did not run in this fixture: the leak is an equity-curve
        // phenomenon and this test is about the S1/S2 gates seeing it.
    };
    let assessment = assess(&criteria, &evidence, None);

    assert_eq!(
        assessment.verdict,
        Verdict::Kill,
        "THE DETECTOR MUST FIRE. The permutation null is what catches this leak, and it catches \
         it by asking a question no statistic computed on the run can answer.\n\nreasons:\n{}",
        assessment.rendered_reasons().join("\n")
    );
    assert_eq!(
        assessment.decided_at,
        Stage::S3,
        "and it must die at S3 — the permutation null — not earlier"
    );

    // The shape of the catch is the point, so it is asserted rather than
    // described: EVERY gate before S3 passes. If a future change made the leak
    // die at S1 or S2 instead, this test would still be green on the verdict
    // while no longer measuring what it claims to.
    for r in &assessment.reasons {
        if r.stage < Stage::S3 {
            assert!(
                r.passed,
                "a gate before S3 caught the leak, so this test no longer measures the \
                 permutation null: {}",
                r.detail
            );
        }
    }
    assert!(
        assessment
            .reasons
            .iter()
            .any(|r| r.stage == Stage::S3 && !r.passed),
        "S3 is what must have failed"
    );
}

/// The negative control on the record itself: an **honest** version of the
/// same idea, fitted on nothing, is killed by the same criteria on the same
/// bars.
///
/// Without this, `the_planted_leak_is_caught_by_the_permutation_null` would be
/// consistent with "the criteria kill everything", which is a different and
/// much less interesting fact. With it, the pair says exactly what it means:
/// the criteria discriminate between the two strategies rather than refusing
/// both on sight.
#[test]
fn the_same_criteria_kill_an_honest_strategy_on_the_same_data() {
    let events = events();
    let keys = day_keys(events.len());
    let plan = FoldPlan::build(&keys, 101, FOLDS).expect("plans");
    let test_windows: Vec<std::ops::Range<usize>> =
        plan.folds().iter().map(|f| f.test.bars.clone()).collect();

    let mut honest =
        crucible_strategies::Aligned::new(crucible_strategies::SmaCross::new(20, 100, Qty(1)), 101);
    let result = replay(&events, &mut honest, &mut costed());
    let oos = pooled(&result, &test_windows);
    let free_oos = pooled(
        &replay(
            &events,
            &mut crucible_strategies::Aligned::new(
                crucible_strategies::SmaCross::new(20, 100, Qty(1)),
                101,
            ),
            &mut FreeFills,
        ),
        &test_windows,
    );

    let evidence = Evidence {
        oos_trades: oos.round_trips,
        oos_sessions: plan.folds().iter().map(|f| f.test.n_days()).sum(),
        free_fill_return_pct: free_oos.total_return_pct,
        costed_return_pct: oos.total_return_pct,
        costed_sharpe: oos.sharpe_naive,
        sharpe_at_kill_level: oos.sharpe_naive,
        random_entry_return_pct: Some(0.0),
        buy_and_hold_return_pct: Some(0.0),
        // The honest strategy is judged by the same criteria, so it needs a
        // p-value too; it is killed at S2 long before S3 is reached.
        permutation_p_value: Some(0.5),
        // Same reasoning as above, and the same care: this converse asserts the
        // honest strategy dies at S2, so S3 must not be what kills it.
        deflated: Some(crucible_funnel::stats::deflated::Deflated {
            observed_sharpe: 4.0,
            expected_max_sharpe: 0.5,
            standard_error: 0.1,
            dsr: 0.999,
            n_trials: 1,
        }),
        n_trials: 1,
        pbo: Some(0.0),
    };
    let assessment = assess(&criteria(), &evidence, None);
    assert_eq!(
        assessment.verdict,
        Verdict::Kill,
        "a crossover on a random walk must die, or the gates are not gates: {:?}",
        assessment.rendered_reasons()
    );
}

fn criteria() -> Criteria {
    let stages = vec!["s1".to_owned(), "s2".to_owned()];
    Criteria::new(&CriteriaSource {
        stages: &stages,
        cost_sensitivity_ticks: &[0.0, 0.5, 1.0, 2.0],
        min_oos_trades: 5,
        min_oos_sessions: 4,
        min_oos_return_pct_free_fills: 0.0,
        min_oos_sharpe_after_costs: 0.5,
        kill_if_dead_at_ticks: 1.0,
        require_controls_beaten: true,
        max_pbo: 0.5,
        require_plateau: true,
        s0_min_abs_ic: None,
        // Pre-registered: the observed edge must be in the top 5 % of what this
        // same strategy produces on block-shuffled series.
        max_permutation_p: Some(0.05),
    })
    .expect("the smoke config's criteria")
}

/// `(open bar, close bar, direction)` for every round-trip, by the same
/// timestamp join the runner uses.
fn round_trips(
    result: &crucible_engine::BacktestResult,
    _events: &[MarketEvent],
) -> Vec<(usize, usize, Side)> {
    let index_of = |ts: Ts| result.equity.partition_point(|&(t, _)| t < ts);
    result
        .closed_trades
        .iter()
        .filter_map(|t| {
            let (open, close) = (index_of(t.opened_ts), index_of(t.closed_ts));
            (close < result.equity.len()).then_some((open, close, t.direction))
        })
        .collect()
}
