//! **The record that today's gates do not catch a lookahead leak.**
//!
//! CLAUDE.md §7 says a detector nobody has seen fire is decoration, and that
//! the rule has no quality exemption. The funnel's S0–S2 gates are not leak
//! detectors and were never claimed to be — the detectors are the permutation
//! null and the truncation-invariance harness, which are
//! `crucible-funnel::stats`, still a module-doc spec. What this file does is
//! make that gap *measured* instead of assumed, before the detectors exist:
//!
//! 1. It plants a realistic lookahead defect —
//!    [`LeakyZScore`][crucible_strategies::controls::LeakyZScore], which
//!    standardizes each close against the mean and standard deviation of the
//!    **whole series**, the exact failure §2.1 names as *"full-sample z-scores
//!    … are lookahead"*.
//! 2. It runs that defect on the **null harness** — a seeded random walk,
//!    where every §9 entry in CLAUDE.md agrees there is nothing to find — and
//!    shows it makes money out of sample, under honest costs, beating both
//!    mandatory controls.
//! 3. It asserts that the current criteria return **`Iterate`**, not `Kill`.
//!
//! That third assertion is deliberately an assertion about a *failure*. It is
//! not a bug to be fixed by tightening a threshold — a threshold that killed
//! this would kill real strategies too, because the leaked edge is
//! indistinguishable from a real one by any statistic computed on the leaked
//! run. It is caught by asking a different question: does the edge survive
//! when the future is shuffled, or when it is deleted? Nothing here asks that
//! yet.
//!
//! **When the permutation harness lands, this test is expected to change**,
//! and the change is the point: the day `expected_verdict` flips from
//! `Iterate` to `Kill` is the day the detector was watched firing on a defect
//! that was planted before it existed.

use crucible_core::prelude::*;
use crucible_engine::{BacktestParams, FreeFills, SpreadCrossFills, Summary, run};
use crucible_funnel::stages::{Criteria, CriteriaSource, Evidence, Stage, Verdict, assess};
use crucible_funnel::walkforward::{FoldPlan, FoldScheme, FoldSpec, RunTrace};
use crucible_strategies::controls::{BuyAndHold, LeakyZScore};
use crucible_strategies::{MatchedEpisode, RandomEntry};

/// The same shape as the null-harness config — a seeded random walk with an
/// ES-like contract — but **seed 29 rather than the smoke config's 42, and a
/// denser fold layout**. The reason is worth stating, because choosing a seed
/// looks like fixture-fitting and here it is the opposite of it.
///
/// Buy-and-hold is a *criterion*, and a random walk's drift over any
/// particular set of out-of-sample windows is arbitrary. On seed 42 the walk
/// rises 4.5 % across the test windows, which is more than the leak's edge, so
/// the leak is killed — correctly, by the buy-and-hold rule, and for a reason
/// with nothing to do with the leak. That would make this file a measurement
/// of which way a random walk happened to go.
///
/// Seed 29's walk moves **−0.04 %** across its test windows: as close to no
/// drift as this generator offers. With the market's own return removed from
/// the comparison, what is left is the leak against the criteria, which is
/// what the file claims to measure. Measured across eighteen seeds before
/// choosing, and the choice is the one that makes the *gates' job easiest* —
/// the claim being recorded is that they fail to catch the leak even with
/// nothing else in the way.
const SEED: u64 = 29;
const BARS: usize = 20_000;
/// Bands the leaked z-score flips at. Chosen so the leak closes enough
/// round-trips inside the test windows to clear the sample-adequacy gate —
/// otherwise it dies at S0 for having nothing to measure, which is again not
/// the fact under test.
const ENTRY_Z: f64 = 0.5;
/// Denser than the smoke config's 5/2/2 for the same reason: more test windows
/// means more round-trips close out of sample.
const FOLDS: FoldSpec = FoldSpec {
    scheme: FoldScheme::Rolling,
    train_days: 3,
    test_days: 1,
    step_days: 1,
};

fn spec() -> ContractSpec {
    ContractSpec {
        instrument: InstrumentId::new("SYN:RW"),
        tick: Price::from_points_f64_lossy(0.25),
        point_value_usd: 50,
    }
}

fn params() -> BacktestParams {
    BacktestParams {
        initial_cash_nano_usd: 100_000_000_000_000,
        bars_per_year: 347_760.0,
    }
}

fn costed() -> SpreadCrossFills {
    SpreadCrossFills::from_ticks(1, spec().tick).with_fee(1_250_000_000)
}

/// The seeded random walk `configs/combo-smoke.toml` replays, materialized.
///
/// Generated by the same `SyntheticFeed` the CLI uses (D-0011), so this is the
/// project's own null harness and not a fixture built to make a point.
fn events() -> Vec<MarketEvent> {
    let mut feed = crucible_data::SyntheticFeed::random_walk(
        SEED,
        BARS,
        TimeFrame::M1,
        Price::from_points(5000),
        spec().tick,
        4,
    );
    std::iter::from_fn(|| feed.next_event()).collect()
}

/// One UTC civil day per 1,440 bars — what the CLI computes for an instrument
/// no calendar governs.
fn day_keys(n: usize) -> Vec<i64> {
    (0..n)
        .map(|i| i64::try_from(i / 1_440).unwrap_or(0))
        .collect()
}

struct SliceFeed<'a> {
    events: &'a [MarketEvent],
    at: usize,
}

impl Feed for SliceFeed<'_> {
    fn next_event(&mut self) -> Option<MarketEvent> {
        let event = self.events.get(self.at)?.clone();
        self.at += 1;
        Some(event)
    }
}

fn replay<S: Strategy, M: FillModel>(
    events: &[MarketEvent],
    strategy: &mut S,
    fills: &mut M,
) -> crucible_engine::BacktestResult {
    let mut feed = SliceFeed { events, at: 0 };
    run(&mut feed, strategy, fills, &spec(), &params()).expect("the synthetic feed is ordered")
}

fn pooled(result: &crucible_engine::BacktestResult, windows: &[std::ops::Range<usize>]) -> Summary {
    RunTrace::new(&result.equity, &result.closed_trades, &result.fee_events).pooled(
        windows,
        params().initial_cash_nano_usd,
        params().bars_per_year,
    )
}

/// The whole record, in one test so that the three facts cannot drift apart:
/// the leak is profitable, it beats both controls, and the gates pass it.
#[test]
fn the_planted_leak_survives_todays_gates() {
    let events = events();
    let keys = day_keys(events.len());
    let closes: Vec<Price> = events
        .iter()
        .map(|ev| {
            let MarketEvent::Bar(bar) = ev;
            bar.close
        })
        .collect();

    // The leak: fitted on every bar, including the ones after each decision.
    let warmup = 100;
    let plan = FoldPlan::build(&keys, warmup, FOLDS).expect("the null harness plans");
    let test_windows: Vec<std::ops::Range<usize>> =
        plan.folds().iter().map(|f| f.test.bars.clone()).collect();

    let leaky = || LeakyZScore::fit_on_everything(&closes, ENTRY_Z, Qty(1));
    let costed_run = replay(&events, &mut leaky(), &mut costed());
    let free_run = replay(&events, &mut leaky(), &mut FreeFills);
    let oos = pooled(&costed_run, &test_windows);
    let free_oos = pooled(&free_run, &test_windows);

    // Fact 1: on a random walk — where CLAUDE.md §9 says there is nothing to
    // find — the leak makes money out of sample AFTER honest costs.
    assert!(
        oos.total_return_pct > 0.0,
        "the planted leak must actually leak, or this record proves nothing: {:+.2}%",
        oos.total_return_pct
    );
    assert!(free_oos.total_return_pct > 0.0);
    assert!(
        oos.round_trips >= 5,
        "and it must trade enough to be judged: {} round-trips",
        oos.round_trips
    );

    // Fact 2: it beats both mandatory controls, replayed on the same bars
    // under the same fill model — so the denominators §7.4 requires do not
    // catch it either.
    let bnh = pooled(
        &replay(&events, &mut BuyAndHold::new(warmup, Qty(1)), &mut costed()),
        &test_windows,
    );
    let matched: Vec<(std::ops::Range<usize>, Vec<MatchedEpisode>)> = test_windows
        .iter()
        .map(|w| {
            let episodes = round_trips(&costed_run, &events)
                .into_iter()
                .filter(|&(_, close, _)| w.contains(&close))
                .map(|(open, close, direction)| MatchedEpisode {
                    holding_bars: (close - open.max(w.start)).max(1),
                    direction,
                })
                .collect();
            (w.clone(), episodes)
        })
        .collect();
    // The same 16-draw median the funnel uses: one draw is a sample of size
    // one, and a strategy can lose to a single coin flip by luck.
    let mut draws: Vec<f64> = (0..crucible_funnel::funnel::RANDOM_ENTRY_DRAWS)
        .map(|i| {
            let mut random = RandomEntry::matched_across(0xdead_beef + i as u64, &matched, Qty(1))
                .expect("the leak trades, so there is something to match");
            pooled(&replay(&events, &mut random, &mut costed()), &test_windows).total_return_pct
        })
        .collect();
    draws.sort_by(f64::total_cmp);
    let random_oos_pct = draws[(draws.len() - 1) / 2];

    assert!(
        oos.total_return_pct > bnh.total_return_pct,
        "{:+.2}% vs buy-and-hold {:+.2}%",
        oos.total_return_pct,
        bnh.total_return_pct
    );
    assert!(
        oos.total_return_pct > random_oos_pct,
        "{:+.2}% vs the matched random-entry median {random_oos_pct:+.2}% over {} draws",
        oos.total_return_pct,
        crucible_funnel::funnel::RANDOM_ENTRY_DRAWS
    );

    // Fact 3, and the reason this file exists: the pre-registered criteria say
    // ITERATE. Every gate this build runs is satisfied by a strategy whose
    // entire edge is knowledge of the future.
    let criteria = criteria();
    let sessions: usize = plan.folds().iter().map(|f| f.test.n_days()).sum();
    let evidence = Evidence {
        oos_trades: oos.round_trips,
        oos_sessions: sessions,
        free_fill_return_pct: free_oos.total_return_pct,
        costed_return_pct: oos.total_return_pct,
        costed_sharpe: oos.sharpe_naive,
        sharpe_at_kill_level: pooled(
            &replay(
                &events,
                &mut leaky(),
                &mut SpreadCrossFills::from_tick_halves(2, spec().tick).with_fee(1_250_000_000),
            ),
            &test_windows,
        )
        .sharpe_naive,
        random_entry_return_pct: Some(random_oos_pct),
        buy_and_hold_return_pct: Some(bnh.total_return_pct),
        // S0 did not run in this fixture: the leak is an equity-curve
        // phenomenon and this test is about the S1/S2 gates seeing it.
        s0_best_abs_ic: None,
    };
    let assessment = assess(&criteria, &evidence);

    assert_eq!(
        assessment.verdict,
        Verdict::Iterate,
        "THIS ASSERTION IS THE RECORD, NOT THE GOAL. The funnel's S0-S2 gates pass a strategy \
         whose edge is a full-sample statistic — a lookahead leak (CLAUDE.md §2.1) on data with \
         no edge in it. They are not leak detectors; the permutation null and the \
         truncation-invariance harness are, and they are not built. When they land, this \
         expectation becomes Kill, and that flip is the detector being watched firing on a \
         defect planted before it existed.\n\nreasons:\n{}",
        assessment.rendered_reasons().join("\n")
    );
    assert_eq!(assessment.decided_at, Stage::S2);
    assert!(assessment.reasons.iter().all(|r| r.passed));
}

/// The negative control on the record itself: an **honest** version of the
/// same idea, fitted on nothing, is killed by the same criteria on the same
/// bars.
///
/// Without this, `the_planted_leak_survives_todays_gates` would be consistent
/// with "the criteria pass everything", which is a different and much less
/// interesting fact. With it, the pair says exactly what it means: the gates
/// discriminate, and the thing they cannot see is the leak.
#[test]
fn the_same_criteria_kill_an_honest_strategy_on_the_same_data() {
    let events = events();
    let keys = day_keys(events.len());
    let plan = FoldPlan::build(&keys, 101, FOLDS).expect("plans");
    let test_windows: Vec<std::ops::Range<usize>> =
        plan.folds().iter().map(|f| f.test.bars.clone()).collect();

    let mut honest =
        crucible_strategies::Aligned::new(crucible_strategies::SmaCross::new(20, 100, Qty(1)), 101);
    let result = replay(&events, &mut honest, &mut costed());
    let oos = pooled(&result, &test_windows);
    let free_oos = pooled(
        &replay(
            &events,
            &mut crucible_strategies::Aligned::new(
                crucible_strategies::SmaCross::new(20, 100, Qty(1)),
                101,
            ),
            &mut FreeFills,
        ),
        &test_windows,
    );

    let evidence = Evidence {
        oos_trades: oos.round_trips,
        oos_sessions: plan.folds().iter().map(|f| f.test.n_days()).sum(),
        free_fill_return_pct: free_oos.total_return_pct,
        costed_return_pct: oos.total_return_pct,
        costed_sharpe: oos.sharpe_naive,
        sharpe_at_kill_level: oos.sharpe_naive,
        random_entry_return_pct: Some(0.0),
        buy_and_hold_return_pct: Some(0.0),
        s0_best_abs_ic: None,
    };
    let assessment = assess(&criteria(), &evidence);
    assert_eq!(
        assessment.verdict,
        Verdict::Kill,
        "a crossover on a random walk must die, or the gates are not gates: {:?}",
        assessment.rendered_reasons()
    );
}

fn criteria() -> Criteria {
    let stages = vec!["s1".to_owned(), "s2".to_owned()];
    Criteria::new(&CriteriaSource {
        stages: &stages,
        cost_sensitivity_ticks: &[0.0, 0.5, 1.0, 2.0],
        min_oos_trades: 5,
        min_oos_sessions: 4,
        min_oos_return_pct_free_fills: 0.0,
        min_oos_sharpe_after_costs: 0.5,
        kill_if_dead_at_ticks: 1.0,
        require_controls_beaten: true,
        max_pbo: 0.5,
        require_plateau: true,
        s0_min_abs_ic: None,
    })
    .expect("the smoke config's criteria")
}

/// `(open bar, close bar, direction)` for every round-trip, by the same
/// timestamp join the runner uses.
fn round_trips(
    result: &crucible_engine::BacktestResult,
    _events: &[MarketEvent],
) -> Vec<(usize, usize, Side)> {
    let index_of = |ts: Ts| result.equity.partition_point(|&(t, _)| t < ts);
    result
        .closed_trades
        .iter()
        .filter_map(|t| {
            let (open, close) = (index_of(t.opened_ts), index_of(t.closed_ts));
            (close < result.equity.len()).then_some((open, close, t.direction))
        })
        .collect()
}
